"""
=============================================================================
DOCS AS CODE: AUTOMATED FEATURE ENGINEERING DOCUMENT GENERATOR
=============================================================================
This script parses the config.yaml file and dynamically generates the 
FEATURE_ENGINEERING.md documentation. This ensures that the documentation 
is always perfectly aligned with the actual code rules, eliminating 
documentation drift.
"""

import yaml
import os
from pathlib import Path

def load_config(filename="step1_features_config.yaml"):
    """Loads the YAML configuration file."""

    script_dir = Path(__file__).resolve().parent.parent.parent
    config_path = script_dir / 'src' / filename
    
    try:
        with open(config_path, 'r', encoding='utf-8') as file:
            return yaml.safe_load(file)
    except FileNotFoundError:
        print(f"Error: {config_path} not found. Please ensure it exists in the root directory.")
        exit(1)

def build_markdown(config):
    """Builds the Markdown string based on the configuration dictionary."""
    
    # 1. Header & Warning
    md = "# Feature Engineering & Data Mapping Specification\n\n"
    md += "> ⚠️ **WARNING:** This document is automatically generated from `step1_features_config.yaml` using the `build_docs.py` script. **Do not edit this file manually.** All changes must be made directly in the YAML configuration to ensure architectural consistency.\n\n"
    
    md += f"**Data Source:** `{config['pipeline_info']['source_file']}`\n"
    md += f"**Target:** {config['pipeline_info']['target_output']}\n\n"
    md += "---\n\n"

    # 2. Hard Constraints
    md += "## 1. Hard Constraints (Exclusion Filters)\n"
    md += "Business rules applied during the data ingestion phase. Records failing these constraints are summarily dropped.\n\n"
    for constraint in config.get('hard_constraints', []):
        md += f"* **`{constraint['feature']}`**: Must be `{constraint['condition']} {constraint['value']}`\n"
    md += "\n"

    # 3. Dropped Columns
    md += "## 2. Dropped Columns (Zero Variance / Non-Informative)\n"
    md += "Columns removed prior to processing because they lack variance across the filtered dataset.\n\n"
    for col in config['dropped_columns'].get('zero_variance', []):
        md += f"* `{col}`\n"
    md += "\n"

    # 4. Conditional Logic & Feature Substitution (ATUALIZADO)
    md += "## 3. Conditional Logic & Feature Substitution\n"
    md += "Logic applied to handle `NaN` values or to override values based on cross-feature dependencies. This prevents double-penalizing alternatives that lack a feature but possess a functionally superior substitute.\n\n"
    for cond in config.get('conditional_logic', []):
        md += f"* **Target Feature:** `{cond['feature']}`\n"
        md += f"  * **Rule:** {cond['rule']}\n\n"

    # 5. Non-Linear Utility Mapping
    md += "## 4. Non-Linear Utility Mapping (Discretization)\n"
    md += "Manual mapping applied to enforce the economic Law of Diminishing Marginal Utility.\n\n"
    md += "| Feature (Source) | Raw Value | Mapped Utility Score | Business Justification |\n"
    md += "| :--- | :--- | :--- | :--- |\n"
    
    for feature, mappings in config.get('utility_mapping', {}).items():
        first_row = True
        for raw_val, details in mappings.items():
            feature_name = f"**`{feature}`**" if first_row else ""
            md += f"| {feature_name} | `{raw_val}` | ${details['score']}$ | {details['justification']} |\n"
            first_row = False
    md += "\n"

    # 6. Binarization
    md += "## 5. Direct Binarization\n"
    md += "Boolean columns converted directly into numerical scale (`True` -> $1.0$ | `False` -> $0.0$).\n\n"
    md += "* **Applied Columns:** "
    md += ", ".join([f"`{col}`" for col in config.get('direct_binarization', [])])
    md += "\n\n"

    # 7. Continuous Normalization
    md += "## 6. Continuous Normalization (Min-Max Scaling)\n"
    md += "Proportional linear transformation ensuring values fall strictly between $0.0$ and $1.0$.\n\n"
    
    md += "### 6.1. Minimization Criteria (Costs)\n"
    md += "* **Formula:** $Score = \\frac{\\max(X) - X}{\\max(X) - \\min(X)}$\n"
    md += "* **Applied Columns:** "
    md += ", ".join([f"`{col}`" for col in config['continuous_normalization'].get('minimization_costs', [])])
    md += "\n\n"

    md += "### 6.2. Maximization Criteria (Benefits)\n"
    md += "* **Formula:** $Score = \\frac{X - \\min(X)}{\\max(X) - \\min(X)}$\n"
    md += "* **Applied Columns:** "
    md += ", ".join([f"`{col}`" for col in config['continuous_normalization'].get('maximization_benefits', [])])
    md += "\n"

    return md

def save_markdown(md_content, output_file="FEATURE-ENGINEERING.md"):
    """Saves the generated Markdown content to the specified file."""

    script_dir = Path(__file__).resolve().parent.parent.parent
    output_path = script_dir / 'docs' / output_file

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as file:
        file.write(md_content)
    
    print(f"✅ Success! Documentation generated at: {output_path}")

if __name__ == "__main__":
    print("🔄 Building documentation from step1_features_config.yaml...")
    configuration = load_config()
    markdown_output = build_markdown(configuration)
    save_markdown(markdown_output)